services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: desafio_subampro
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d desafio_subampro"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:5
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
